namespace: mysql

serviceAccountName: mysql-sa

image:
  repository: mysql
  tag: "8.0"

secrets:
  MYSQL_ROOT_PASSWORD: "cm9vdHBhc3M="   # base64 encoded
  MYSQL_DATABASE: "dG9kb2Ribg=="        # base64 encoded
  MYSQL_USER: "dXNlcg=="                # base64 encoded
  MYSQL_PASSWORD: "cGFzc3dvcmQ="        # base64 encoded

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

replicaCount: 1

pvc:
  storage: "1Gi"

affinity:
  key: "app"
  values:
    - "mysql"

tolerations:
  - key: "app"
    operator: "Equal"
    value: "mysql"
    effect: "NoSchedule"