namespace:
  name: todoapp-ns

image:
  repository: mysql
  tag: "8.0"
  pullPolicy: IfNotPresent

replicaCount: 1

resources:
  requests:
    memory: "256Mi"
    cpu: "250m"
  limits:
    memory: "512Mi"
    cpu: "500m"

persistentVolume:
  capacity: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath: /mnt/data

persistentVolumeClaim:
  storage: 2Gi
  accessModes:
    - ReadWriteOnce

affinity:
  nodeAffinity:
    key: app
    values:
      - mysql
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: app
              operator: In
              values:
                - mysql

tolerations:
  - key: "app"
    operator: "Equal"
    value: "mysql"
    effect: "NoSchedule"

secrets:
  MYSQL_ROOT_PASSWORD: "rootpassword123"
  MYSQL_DATABASE: "todoapp"
  MYSQL_USER: "user"
  MYSQL_PASSWORD: "password"

serviceAccount:
  name: todoapp-sa

hpa:
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

rollingUpdate:
  maxSurge: 1
  maxUnavailable: 0
